import { app, BrowserWindow, clipboard, dialog, globalShortcut, ipcMain, nativeImage, safeStorage, screen, systemPreferences } from 'electron';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ClipboardHistoryStore } from './clipboardHistoryStore';
import { captureClipboardPasteTarget, clipboardPopupPosition, type ClipboardPasteTarget } from './clipboardPasteTarget';

export function registerClipboardHistory(isSettingsSender: (id: number) => boolean): void {
  const supported = process.platform !== 'win32';
  const defaultAccelerator = 'Control+Alt+V';
  let store: ClipboardHistoryStore | undefined;
  let problem = '';
  let registered = '';
  let popup: BrowserWindow | undefined;
  let opening = false;
  let selecting = false;
  let target: ClipboardPasteTarget | undefined;
  let timer: ReturnType<typeof setInterval> | undefined;
  const state = () => ({ supported, accelerator: store?.accelerator ?? defaultAccelerator,
    enabled: store?.enabled ?? false, registered: Boolean(registered), error: problem });
  const notify = () => popup?.webContents.send('clipboard-history:changed');
  const capture = () => {
    if (!store?.enabled || selecting) return;
    try {
      const formats = clipboard.availableFormats();
      if (formats.some(format => /concealed|transient|autogenerated|password/i.test(format))) return;
      const text = clipboard.readText();
      const changed = text ? store.capture('text', text) : (() => {
        const image = clipboard.readImage();
        const size = image.getSize();
        if (size.width * size.height > 4_000_000) return false;
        return store.capture('image', image.isEmpty() ? '' : image.toDataURL());
      })();
      if (changed) notify();
    } catch { problem = 'Clipboard history could not be saved. Check local storage.'; }
  };
  const hide = () => {
    popup?.hide();
    if (!selecting) { target?.dispose(); target = undefined; }
  };
  const restoreAndHide = async () => {
    const previous = target;
    target = undefined;
    popup?.hide();
    try { await previous?.restore(); } finally { previous?.dispose(); }
  };
  const show = async () => {
    if (opening || selecting) return;
    if (popup?.isVisible()) { await restoreAndHide().catch(() => {}); return; }
    opening = true;
    // Snapshot the fallback now; moving the mouse while the helper starts must not move the popup.
    const pointer = screen.getCursorScreenPoint();
    try {
      target?.dispose();
      target = undefined;
      if (process.platform === 'darwin' && !systemPreferences.isTrustedAccessibilityClient(false)) {
        systemPreferences.isTrustedAccessibilityClient(true);
        throw new Error('Allow Service Manager in System Settings > Privacy & Security > Accessibility, then try again.');
      }
      target = await captureClipboardPasteTarget();
      capture();
      if (!popup || popup.isDestroyed()) {
        popup = new BrowserWindow({ width: 360, height: 460, show: false, frame: false,
          resizable: false, alwaysOnTop: true, skipTaskbar: true, title: 'Clipboard history',
          webPreferences: { preload: path.join(__dirname, 'clipboardPreload.js'), sandbox: true,
            contextIsolation: true, nodeIntegration: false } });
        popup.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
        popup.on('blur', hide);
        popup.on('closed', () => { popup = undefined; target?.dispose(); target = undefined; });
        popup.webContents.setWindowOpenHandler(() => ({ action: 'deny' }));
        popup.webContents.on('will-navigate', event => event.preventDefault());
        await popup.loadURL(pathToFileURL(path.join(__dirname, '../../renderer/clipboardHistory.html')).href);
      }
      const anchor = target.anchor ?? { ...pointer, width: 0, height: 0 };
      const area = screen.getDisplayNearestPoint({ x: Math.round(anchor.x), y: Math.round(anchor.y) }).workArea;
      const position = clipboardPopupPosition(anchor, area);
      popup.setPosition(position.x, position.y);
      popup.show();
      app.focus({ steal: true });
      popup.focus();
      notify();
    } catch (error) {
      target?.dispose(); target = undefined;
      problem = error instanceof Error ? error.message : 'Clipboard history could not be opened.';
      void dialog.showMessageBox({ type: 'info', title: 'Clipboard history', message: problem });
    }
    finally { opening = false; }
  };
  const bind = (accelerator: string) => {
    if (!accelerator) return;
    if (!globalShortcut.register(accelerator, () => { void show(); })) {
      throw new Error('Shortcut is unavailable or already in use. Choose another shortcut.');
    }
    registered = accelerator;
  };
  if (supported) {
    try {
      store = new ClipboardHistoryStore(path.join(app.getPath('userData'), 'clipboard-local', 'history.json'), defaultAccelerator,
        text => safeStorage.isEncryptionAvailable() && (process.platform !== 'linux' || safeStorage.getSelectedStorageBackend() !== 'basic_text')
          ? Buffer.concat([Buffer.from('ENC1'), safeStorage.encryptString(text)]) : Buffer.from(text),
        data => data.subarray(0, 4).toString() === 'ENC1' ? safeStorage.decryptString(data.subarray(4)) : data.toString());
      if (store.enabled) bind(store.accelerator);
    } catch { problem = store ? 'Clipboard shortcut could not be registered. Choose another shortcut.'
      : 'Local clipboard history could not be opened. Existing history has been preserved.'; }
    if (store) timer = setInterval(capture, 600);
  }
  ipcMain.handle('settings:shortcuts:get', event => {
    if (!isSettingsSender(event.sender.id)) throw new Error('Unknown settings window.');
    return state();
  });
  ipcMain.handle('settings:shortcuts:save', (event, input: unknown) => {
    if (!isSettingsSender(event.sender.id) || !supported || !store) throw new Error('Clipboard history is unavailable.');
    const draft = input as { accelerator?: unknown; enabled?: unknown };
    if (!draft || typeof draft.enabled !== 'boolean' || typeof draft.accelerator !== 'string'
      || !/^(?:(?:Command|Control|Alt|Shift|Super)\+)+[A-Z0-9]$/.test(draft.accelerator)
      || draft.accelerator.length > 80) throw new Error('Use a modifier and a letter or number.');
    const previous = { accelerator: store.accelerator, enabled: store.enabled, registered };
    if (registered) globalShortcut.unregister(registered);
    registered = '';
    try {
      if (draft.enabled) bind(draft.accelerator);
      store.accelerator = draft.accelerator;
      store.enabled = draft.enabled;
      store.save();
      problem = '';
      if (!store.enabled) hide();
    } catch (error) {
      if (registered) globalShortcut.unregister(registered);
      registered = '';
      store.accelerator = previous.accelerator;
      store.enabled = previous.enabled;
      if (previous.registered) { try { bind(previous.registered); } catch { problem = 'Shortcut registration failed.'; } }
      throw error;
    }
    return state();
  });
  ipcMain.handle('clipboard-history:action', async (event, action: unknown, id: unknown) => {
    if (!popup || event.sender !== popup.webContents || !store) throw new Error('Unknown clipboard window.');
    if (action === 'list') return store.entries;
    if (action === 'close') { await restoreAndHide(); return; }
    if (action === 'clear') { store.forget(); notify(); return; }
    if (typeof id !== 'string') throw new Error('Invalid clipboard entry.');
    const entry = store.entries.find(item => item.id === id);
    if (!entry) throw new Error('Clipboard entry no longer exists.');
    if (action === 'delete') { store.forget(id); notify(); return; }
    if (action !== 'paste' || selecting) return;
    if (!popup.isVisible() || !target) throw new Error('Return to the text field and reopen clipboard history.');
    const pasteTarget = target;
    selecting = true;
    const shortcut = registered;
    try {
      if (entry.kind === 'text') clipboard.writeText(entry.value);
      else clipboard.writeImage(nativeImage.createFromDataURL(entry.value));
      popup.hide();
      // A user may assign Cmd+V itself; synthetic paste must not reopen history.
      if (shortcut) globalShortcut.unregister(shortcut);
      registered = '';
      await pasteTarget.paste();
      try { store.capture(entry.kind, entry.value); }
      catch { problem = 'Clipboard history could not be saved. Check local storage.'; }
    } catch (error) {
      popup.show();
      app.focus({ steal: true });
      popup.focus();
      throw error;
    } finally {
      pasteTarget.dispose();
      target = undefined;
      if (shortcut && store.enabled && !registered) {
        try { bind(shortcut); } catch { problem = 'Clipboard shortcut could not be restored.'; }
      }
      selecting = false;
    }
  });
  app.on('will-quit', () => {
    if (timer) clearInterval(timer);
    target?.dispose();
    if (registered) globalShortcut.unregister(registered);
  });
}
